source: "local-seed"
inputs:
  pdf_dir: "data/raw/pmc/seed"     # put a few OA PDFs here
  html_dir: "data/raw/web/seed"    # optional: OA HTML pages here
licenses:
  allowed: ["CC-BY-4.0","CC-BY-3.0","CC-BY-SA-4.0","CC0-1.0","US-Gov-PD","Public-Domain"]
defaults:
  language: "en"
